// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdnwzXEmFWrIs2bkIg7CFxTAjBsVe-LnQ',
    appId: '1:369074098860:web:384636fe6b9e87d9b4c509',
    messagingSenderId: '369074098860',
    projectId: 'login-27d96',
    authDomain: 'login-27d96.firebaseapp.com',
    storageBucket: 'login-27d96.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC4Bc_iYi36K-0h71a1zkQ7VoCM1Cx8dA',
    appId: '1:369074098860:android:a2550df7112e53bbb4c509',
    messagingSenderId: '369074098860',
    projectId: 'login-27d96',
    storageBucket: 'login-27d96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHAEbrFZ6AdXMlKvUlmELrxbwI1zCfoJU',
    appId: '1:369074098860:ios:45d88ea4de2552d3b4c509',
    messagingSenderId: '369074098860',
    projectId: 'login-27d96',
    storageBucket: 'login-27d96.appspot.com',
    iosClientId: '369074098860-khnksos7nll4m1b2l8o7243a88vgo641.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHAEbrFZ6AdXMlKvUlmELrxbwI1zCfoJU',
    appId: '1:369074098860:ios:ddcfd0fc06cd0aa8b4c509',
    messagingSenderId: '369074098860',
    projectId: 'login-27d96',
    storageBucket: 'login-27d96.appspot.com',
    iosClientId: '369074098860-u8cfgvmq5odsm4cd1g23aqdmjo6a4492.apps.googleusercontent.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
